_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 7
                - 55
            "2":
                - 7
                - 55
            "3":
                - 5
                - 14
                - 23
                - 55
                - 62
            "4": 3.12.8
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
        visualize:
            pr:
                panel_config:
                    fieldSettings:
                        class: class
                        x: recall
                        "y": precision
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Recall Curve
                        x-axis-title: Recall
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: pr_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
