_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 15
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.4
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
